### DISCUSSION TITLE
Passing strings through a compute circuit

### DISCUSSION THREAD

**Discussion by wwwehr** [NillionNetwork/discussions#8] [Show and tell]
I'm experimenting to see how I can pass messages along data into a circuit so that the result party can use it.

Certainly this has holes in it's concept, but could be interesting strategy for app builders until we can properly support this kind of thing.

I want to build a circuit where all dealers input an integer but also provide their public wallet address. This way, when the circuit computes an outcome, the dealers address is sent with the result output to the result dealer (not the program executor).

```python3
import yaml


def yaml_template(i: list[str]) -> str:
    as_yaml_config = yaml.dump(
        {
            "public_variables": {
                "inner_type": "Integer",
                "values": [{"Integer": x} for x in i],
            }
        }
    )
    return as_yaml_config


def string_to_secrets(s: str) -> list[str]:
    return [ord(c) for c in s]


def secrets_to_string(i: list[str]) -> str:
    return "".join([chr(int(x)) for x in i])


if __name__ == '__main__':
    uuid = "0xd3b2d560E1df7d840c049239898483cf17B830Ba"
    
    int_array = string_to_secrets(uuid)
    yaml_nada_section = yaml_template(int_array)
    print(yaml_nada_section)
    
    decoded_uuid = secrets_to_string(int_array)
    assert(uuid == decoded_uuid)
```

Since I'm using the [nada](https://docs.nillion.com/nada) tool for developing my circuit, this above python script will poop out a yaml section that I can easily integrate into my `tests/` dir.

```yaml
public_variables:
  INPUT_NAME:
    Array:
      inner_type: Integer
      values:
      - Integer: 48
      - Integer: 120
      - Integer: 100
      - Integer: 51
      - Integer: 98
      - Integer: 50
      - Integer: 100
      - Integer: 53
      - Integer: 54
      - Integer: 48
      - Integer: 69
      - Integer: 49
      - Integer: 100
      - Integer: 102
      - Integer: 55
      - Integer: 100
      - Integer: 56
      - Integer: 52
      - Integer: 48
      - Integer: 99
      - Integer: 48
      - Integer: 52
      - Integer: 57
      - Integer: 50
      - Integer: 51
      - Integer: 57
      - Integer: 56
      - Integer: 57
      - Integer: 56
      - Integer: 52
      - Integer: 56
      - Integer: 51
      - Integer: 99
      - Integer: 102
      - Integer: 49
      - Integer: 55
      - Integer: 66
      - Integer: 56
      - Integer: 51
      - Integer: 48
      - Integer: 66
      - Integer: 97
```

In a real application, I would instead use the functions above so that I can create Secrets with them and pass into the compute() function as usual.

Hope this is helpful! Add comments or questions below.
